'use client';
import {useEffect,useState} from 'react';
import {carriers,modelInfo} from '../lib/carriers';
import {estimateAll} from '../lib/estimate';
import {estimateReplacementCost,replacementCostProvider} from '../lib/replacement-cost';
import Nav from '../components/Nav';

const initial={first:'',last:'',email:'',zip:'',address:'',dob:'',roof:'',yearBuilt:'',squareFeet:'',stories:'1',finishQuality:'standard',garage:'two_car',detachedStructures:'none',occupancy:'primary',construction:'frame',homeDeductible:'2500',homeClaims:'0',vehicleUse:'commute',annualMiles:'average',priorInsurance:'continuous',accidents:'0',tickets:'0'};
const options={
  vehicleUse:[['pleasure','Pleasure'],['commute','Commute'],['business','Business']],
  annualMiles:[['low','Under 7,500'],['average','7,500–15,000'],['high','Over 15,000']],
  priorInsurance:[['continuous','Continuous—no lapse'],['lapse','Lapse within 12 months'],['none','No current insurance']],
  count:[['0','None'],['1','1'],['2','2'],['3','3+']],
  occupancy:[['primary','Primary residence'],['secondary','Secondary residence'],['rental','Rental']],
  construction:[['frame','Frame'],['masonry','Masonry'],['manufactured','Manufactured home'],['log','Log home']],
  deductible:[['1000','$1,000'],['2500','$2,500'],['5000','$5,000']],
  stories:[['1','1 story'],['1.5','1½ stories'],['2','2 stories'],['3','3 stories']],
  finish:[['basic','Basic'],['standard','Standard'],['upgraded','Upgraded'],['custom','Custom/high-end']],
  garage:[['none','No attached garage'],['one_car','1-car garage'],['two_car','2-car garage'],['three_car','3-car garage']],
  detached:[['none','None'],['small','Small shed or similar'],['garage','Detached garage/workshop'],['substantial','Multiple or substantial structures']]
};

export default function App(){
  const[tab,setTab]=useState('hunt'),[type,setType]=useState(null),[step,setStep]=useState(0),[profile,setProfile]=useState('Recommended');
  const[form,setForm]=useState(initial),[drivers,setDrivers]=useState([{first:'',last:'',dob:''}]),[vehicles,setVehicles]=useState([{year:'',make:'',model:''}]);
  const[results,setResults]=useState([]),[hunts,setHunts]=useState([]),[handoff,setHandoff]=useState(null),[showMethod,setShowMethod]=useState(false);
  const replacement=estimateReplacementCost(form);
  useEffect(()=>{fetch('/api/rate-hunts').then(r=>r.json()).then(j=>setHunts(j.hunts||[])).catch(()=>{})},[]);
  const update=(k,v)=>setForm(x=>({...x,[k]:v}));
  const field=(k,l,t='text',p={})=><label>{l}<input type={t} value={form[k]} onChange={e=>update(k,e.target.value)} {...p}/></label>;
  const select=(k,l,o)=><label>{l}<select value={form[k]} onChange={e=>update(k,e.target.value)}>{o.map(x=><option value={x[0]} key={x[0]}>{x[1]}</option>)}</select></label>;
  const df=(i,k,l,t='text')=><label>{l}<input type={t} value={drivers[i][k]} onChange={e=>setDrivers(v=>v.map((x,n)=>n===i?{...x,[k]:e.target.value}:x))}/></label>;
  const vf=(i,k,l)=><label>{l}<input value={vehicles[i][k]} onChange={e=>setVehicles(v=>v.map((x,n)=>n===i?{...x,[k]:e.target.value}:x))}/></label>;
  async function run(){setStep(4);const intake={...form,drivers,vehicles},modeled=estimateAll(carriers,type,intake,profile);try{const x=await fetch('/api/rate-hunts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({searchType:type,coverageProfile:profile,stateCode:'NM',modelVersion:modelInfo.version,intake,estimates:modeled.map(({n,low,estimate,high})=>({carrier:n,low,midpoint:estimate,high}))})});const j=await x.json();if(j.hunt)setHunts(v=>[j.hunt,...v])}catch{}setTimeout(()=>{setResults(modeled);setStep(5)},650)}
  async function approve(){const c=handoff;await fetch('/api/consent',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({carrier:c.n,fields:[],mode:c.connection})}).catch(()=>{});window.open(type==='home'?c.hu:c.au||c.hu,'_blank');setHandoff(null)}
  return <main><header><div className="mark">RH</div><div><strong>RateHunt</strong><small>Personalized estimate engine</small></div><span>● V4.3</span></header>
  {tab==='hunt'&&<>{step===0&&<section className="hero"><small>RATEHUNT · NEW MEXICO</small><h1>One hunt.<br/>Better choices.</h1><p>Get a personalized planning range for Auto, Home, or both—then continue with the carrier for a final quote.</p><div className="types">{[['auto','🚗','Auto'],['home','🏠','Home'],['bundle','🏠 + 🚗','Home + Auto']].map(x=><button key={x[0]} className={type===x[0]?'on':''} onClick={()=>setType(x[0])}><i>{x[1]}</i><b>{x[2]}</b><small>{x[0]==='bundle'?'Estimate a bundled policy':'Estimate '+x[2].toLowerCase()+' coverage'}</small></button>)}</div><button className="primary" disabled={!type} onClick={()=>setStep(1)}>Start my RateHunt →</button></section>}
  {step===1&&<section className="card"><Step count="1 of 3" title="Let's start with the basics."/><div className="grid">{field('first','First name')}{field('last','Last name')}{field('email','Email','email')}{field('zip','ZIP code','text',{inputMode:'numeric',maxLength:5})}{field('dob','Primary applicant birth date','date')}{type!=='auto'&&field('address','Home address')}</div><Actions back={()=>setStep(0)} next={()=>setStep(2)}/></section>}
  {step===2&&<section className="card"><Step count="2 of 3" title={type==='home'?'Tell us about the home.':type==='auto'?'Drivers and vehicles.':'Auto and home details.'}/>
    {type!=='home'&&<><h3>Drivers</h3>{drivers.map((d,i)=><div className="vehicle" key={'d'+i}><div className="vehicleHead"><b>Driver {i+1}</b>{drivers.length>1&&<button onClick={()=>setDrivers(v=>v.filter((_,n)=>n!==i))}>Remove</button>}</div><div className="grid">{df(i,'first','First name')}{df(i,'last','Last name')}{df(i,'dob','Date of birth','date')}</div></div>)}<button className="addVehicle" onClick={()=>setDrivers(v=>[...v,{first:'',last:'',dob:''}])}>+ Add another driver</button>
    <h3>Vehicles</h3>{vehicles.map((v,i)=><div className="vehicle" key={'v'+i}><div className="vehicleHead"><b>Vehicle {i+1}</b>{vehicles.length>1&&<button onClick={()=>setVehicles(vs=>vs.filter((_,n)=>n!==i))}>Remove</button>}</div><div className="grid">{vf(i,'year','Vehicle year')}{vf(i,'make','Vehicle make')}{vf(i,'model','Vehicle model')}</div></div>)}<button className="addVehicle" onClick={()=>setVehicles(v=>[...v,{year:'',make:'',model:''}])}>+ Add another vehicle</button>
    <h3>Driving profile</h3><div className="grid">{select('vehicleUse','Primary vehicle use',options.vehicleUse)}{select('annualMiles','Annual mileage',options.annualMiles)}{select('priorInsurance','Prior insurance',options.priorInsurance)}{select('accidents','At-fault accidents—last 5 years',options.count)}{select('tickets','Moving violations—last 3 years',options.count)}</div></>}
    {type!=='auto'&&<><h3>Home profile</h3><p>Tell us what you know. RateHunt will estimate the reconstruction range—you do not need to guess the dwelling limit.</p><div className="grid">{field('squareFeet','Approximate finished square footage','number')}{field('yearBuilt','Year built','number')}{field('roof','Roof replacement year','number')}{select('stories','Number of stories',options.stories)}{select('construction','Construction',options.construction)}{select('finishQuality','Interior finish level',options.finish)}{select('garage','Attached garage',options.garage)}{select('detachedStructures','Detached structures',options.detached)}{select('occupancy','Occupancy',options.occupancy)}{select('homeDeductible','All-peril deductible',options.deductible)}{select('homeClaims','Property claims—last 5 years',options.count)}</div></>}
    <div className="note">No consumer report, MVR, claims database, or insurance score is being ordered. Final carrier quotes can differ after those reports and full underwriting.</div><Actions back={()=>setStep(1)} next={()=>setStep(3)} label="Coverage →"/></section>}
  {step===3&&<section className="card"><Step count="3 of 3" title="Choose a coverage level."/>{type!=='auto'&&<div className="note"><small>PRELIMINARY RECONSTRUCTION RANGE</small><h3>{'$'+replacement.low.toLocaleString()+'–$'+replacement.high.toLocaleString()}</h3><b>{replacementCostProvider.current}</b><br/>Prepared for future {replacementCostProvider.preferred} verification. This is not yet a 360Value result.</div>}<div className="profiles">{[['Basic','Lower limits and higher deductibles'],['Recommended','Balanced protection'],['Enhanced','Higher limits and broader protection']].map(x=><button key={x[0]} className={profile===x[0]?'on':''} onClick={()=>setProfile(x[0])}><b>{x[0]}</b><small>{x[1]}</small></button>)}</div><div className="note"><b>Accuracy promise</b><br/>RateHunt shows a range because a single exact number would imply carrier data we do not yet have.</div><Actions back={()=>setStep(2)} next={run} label="Calculate estimates →"/></section>}
  {step===4&&<section className="card center"><div className="radar">RH</div><h2>Calculating your planning ranges…</h2></section>}
  {step===5&&<section className="card"><div className="resultIntro"><div><small>PERSONALIZED PLANNING ESTIMATES · {modelInfo.version}</small><h2>Your RateHunt results.</h2><p>These estimates respond to the details you entered. They are not live carrier quotes.</p></div><button onClick={()=>setShowMethod(true)}>How this works</button></div><div className="results">{results.map((c,i)=><article key={c.n}><div><h3>{c.n}</h3><span>{type==='bundle'?'Auto + Home':type==='auto'?'Auto':'Home'} · {c.connection}</span>{c.note&&<span>{c.note}</span>}</div><div><small>ESTIMATED RANGE</small><strong>{'$'+c.low+'–$'+c.high}</strong><span>per month</span></div><div><small>MIDPOINT</small><strong>{'$'+c.estimate}</strong><span>planning only</span></div>{i===0?<em>Best modeled fit</em>:<span/>}<button className="primary" onClick={()=>setHandoff(c)}>Continue for final quote →</button>{c.reasons?.length>0&&<div className="factors">Key factors: {c.reasons.join(' · ')}</div>}</article>)}</div></section>}</>}
  {tab==='hunts'&&<section className="card"><h2>My RateHunts</h2>{hunts.length?hunts.map(h=><div className="row" key={h.id}><b>{h.search_type}</b><span>{h.coverage_profile}</span><em>{h.status}</em></div>):<p>No saved RateHunts yet.</p>}</section>}
  {tab==='saved'&&<section className="card"><h2>Saved carriers</h2><p>Your shortlist will appear here as carrier connections are added.</p></section>}
  {tab==='more'&&<section className="card"><h2>Carrier connections</h2><div className="menu"><div><span>External</span><b>Available now—continue on carrier site</b></div><div><span>360Value</span><b>Intake ready · API credentials required</b></div><div><span>Prefilled</span><b>Integration-ready intake format</b></div><div><span>Connected quote</span><b>Requires authorized carrier or rater API</b></div><div><span>Consumer reports</span><b>Requires provider, disclosures, and consent</b></div></div></section>}
  <Nav tab={tab} setTab={setTab}/>
  {handoff&&<div className="overlay"><div className="modal"><small>CARRIER HANDOFF · EXTERNAL</small><h2>Continue with {handoff.n}?</h2><p>RateHunt will open {handoff.n}'s website. The carrier will calculate the official premium.</p><div className="note"><b>No intake data will be transferred yet.</b><br/>Prefill will only be enabled through an authorized integration with clear consent.</div><Actions back={()=>setHandoff(null)} next={approve} label="Continue to carrier →"/></div></div>}
  {showMethod&&<div className="overlay"><div className="modal"><small>ESTIMATION METHOD · {modelInfo.version}</small><h2>Transparent by design.</h2><p>RateHunt begins with a New Mexico planning baseline, then adjusts it for driver ages, vehicles, usage, mileage, prior insurance, driving history, and coverage level.</p><p>For homes, RateHunt builds a 360Value-ready property profile from square footage, age, stories, construction, finish quality, garage, roof, occupancy, and detached structures. Until Verisk credentials are connected, the reconstruction amount is a RateHunt preliminary range—not a 360Value result.</p><p>Carrier indexes are directional modeling factors—not filed rates or prices supplied by the carriers.</p><button className="primary full" onClick={()=>setShowMethod(false)}>Got it</button></div></div>}</main>
}
function Step({count,title}){return <><small>STEP {count}</small><h2>{title}</h2></>}
function Actions({back,next,label='Continue →'}){return <div className="actions"><button onClick={back}>Back</button><button className="primary" onClick={next}>{label}</button></div>}
